repositories:
 - name: bitnami
   url: https://charts.bitnami.com/bitnami
   
helmDefaults:
  wait: false
  timeout: 600
  createNamespace: true

releases:
- name: kafka-prod
  namespace: prod
  chart: bitnami/kafka
  set:
  - name: broker.replicaCount
    value: 5
  - name: image.tag
    value: 3.5.2
  - name: listeners.client.protocol
    value: SASL_PLAINTEXT
  - name: listeners.interbroker.protocol
    value: SASL_PLAINTEXT
- name: kafka-dev
  namespace: dev
  chart: bitnami/kafka
  set:
  - name: broker.replicaCount
    value: 1
  - name: controller.replicaCount
    value: 1
  - name: image.tag
    value: latest
  - name: listeners.client.protocol
    value: PLAINTEXT
  - name: listeners.interbroker.protocol
    value: PLAINTEXT