apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-admin
  namespace: default
subjects:
- kind: ServiceAccount
  name: mysql-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: mysql-admin
  apiGroup: rbac.authorization.k8s.io