{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hw3
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: {{ .Values.reclaimPolicy }}
{{- end }}