apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otus
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Otus Project for DZ10
  sourceRepos:
  - 'https://github.com/Kuber-2023-12OTUS/Redrrah_repo.git'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
    name: in-cluster
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'