apiVersion: apps/v1
kind: Deployment
metadata:
  name: dz8-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dz8-nginx
  template:
    metadata:
      labels:
        app: dz8-nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/redrrah/nginx:v5
          ports:
            - containerPort: 8000

        - name: nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter:latest
          args: ["-nginx.scrape-uri", "http://localhost:8000/metrics"]
          ports:
            - name: web
              containerPort: 9113