apiVersion: v1
kind: Service
metadata:
  name: dz8-nginx-service
spec:
  selector:
    app: dz8-nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
    - port: 9113
      targetPort: 9113
      name: metrics