apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuber-pvc
  namespace: homework
spec:
  storageClassName: "hw3"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi