apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otus-cred
  namespace: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: otus-secret-store
    kind: SecretStore
  target:
    name: otus-cred
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cred
